/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
      const { nodes, materials } = useGLTF('models/museum_room.glb')

      console.log(nodes)

      return (
        <group {...props} dispose={null} scale={0.8} rotation={[0, Math.PI/2, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Floor.geometry}
                material={nodes.Floor.material}
                position={[1.774, 0.263, -0.709]}
                rotation={[-Math.PI, 0, 0]}
                scale={[-17.497, -5.164, -13.451]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube004.geometry}
                material={nodes.Cube004.material}
                position={[1.774, 0.263, -14.419]}
                rotation={[-Math.PI, 0, 0]}
                scale={[-18.13, -0.313, -0.516]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube005.geometry}
                material={nodes.Cube005.material}
                position={[19.788, 0.756, -0.652]}
                rotation={[0, Math.PI / 2, 0]}
                scale={[13.782, 0.516, 0.171]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube006.geometry}
                material={nodes.Cube006.material}
                position={[19.786, 0.263, -0.652]}
                rotation={[Math.PI, -Math.PI / 2, 0]}
                scale={[-13.251, -0.313, -0.516]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube.geometry}
                material={nodes.Cube.material}
                position={[1.774, 0.89, -14.557]}
                rotation={[0, 0, -Math.PI]}
                scale={[-0.516, -0.516, -0.36]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001.geometry}
                material={nodes.Cube001.material}
                position={[1.774, 0.263, 13.057]}
                rotation={[-Math.PI, 0, 0]}
                scale={[-18.13, -0.313, -0.516]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube002.geometry}
                material={nodes.Cube002.material}
                position={[1.774, 0.89, 12.919]}
                rotation={[0, 0, -Math.PI]}
                scale={[-0.516, -0.516, -0.36]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube003.geometry}
                material={nodes.Cube003.material}
                position={[-10.811, 3.042, -14.554]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube007.geometry}
                material={materials.Glass}
                position={[-11.279, 2.196, -6.664]}
                scale={[0.123, 0.516, 1.118]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube008.geometry}
                material={materials.Glass}
                position={[-5.082, 2.196, -6.664]}
                scale={[0.123, 0.516, 1.118]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube009.geometry}
                material={materials.Glass}
                position={[1.115, 2.196, -6.664]}
                scale={[0.123, 0.516, 1.118]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube010.geometry}
                material={materials.Glass}
                position={[7.312, 2.196, -6.664]}
                scale={[0.123, 0.516, 1.118]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube011.geometry}
                material={materials.Glass}
                position={[13.509, 2.196, -6.664]}
                scale={[0.123, 0.516, 1.118]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube012.geometry}
                material={materials.Glass}
                position={[-11.279, 2.196, 5.103]}
                rotation={[0, -0.454, 0]}
                scale={[0.117, 0.516, 1.217]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube013.geometry}
                material={materials.Glass}
                position={[-5.082, 2.196, 5.103]}
                rotation={[0, -0.454, 0]}
                scale={[0.117, 0.516, 1.217]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube014.geometry}
                material={materials.Glass}
                position={[1.115, 2.196, 5.103]}
                rotation={[0, -0.454, 0]}
                scale={[0.117, 0.516, 1.217]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube015.geometry}
                material={materials.Glass}
                position={[7.312, 2.196, 5.103]}
                rotation={[0, -0.454, 0]}
                scale={[0.117, 0.516, 1.217]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube016.geometry}
                material={materials.Glass}
                position={[13.509, 2.196, 5.103]}
                rotation={[0, -0.454, 0]}
                scale={[0.117, 0.516, 1.217]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Roof.geometry}
                material={nodes.Roof.material}
                position={[1.774, 5.961, -0.709]}
                rotation={[-Math.PI, 0, 0]}
                scale={[-17.497, -5.164, -13.451]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube017.geometry}
                material={nodes.Cube017.material}
                position={[-7.173, 3.042, -14.554]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube018.geometry}
                material={nodes.Cube018.material}
                position={[-3.602, 3.042, -14.554]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube019.geometry}
                material={nodes.Cube019.material}
                position={[0.036, 3.042, -14.554]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube020.geometry}
                material={nodes.Cube020.material}
                position={[3.589, 3.042, -14.554]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube021.geometry}
                material={nodes.Cube021.material}
                position={[7.227, 3.042, -14.554]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube022.geometry}
                material={nodes.Cube022.material}
                position={[10.797, 3.042, -14.554]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube023.geometry}
                material={nodes.Cube023.material}
                position={[14.435, 3.042, -14.554]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube024.geometry}
                material={nodes.Cube024.material}
                position={[-10.811, 3.042, 12.91]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube025.geometry}
                material={nodes.Cube025.material}
                position={[-7.173, 3.042, 12.91]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube026.geometry}
                material={nodes.Cube026.material}
                position={[-3.602, 3.042, 12.91]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube027.geometry}
                material={nodes.Cube027.material}
                position={[0.036, 3.042, 12.91]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube028.geometry}
                material={nodes.Cube028.material}
                position={[3.589, 3.042, 12.91]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube029.geometry}
                material={nodes.Cube029.material}
                position={[7.227, 3.042, 12.91]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube030.geometry}
                material={nodes.Cube030.material}
                position={[10.797, 3.042, 12.91]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube031.geometry}
                material={nodes.Cube031.material}
                position={[14.435, 3.042, 12.91]}
                scale={[1.419, 0.111, 0.052]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube032.geometry}
                material={nodes.Cube032.material}
                position={[-7.173, 3.042, 12.91]}
                scale={[1.419, 0.111, 0.052]}
              />
        </group>
      )
}

useGLTF.preload('/museum_room.glb')
